allowBuilds:
  '@openrouter/sdk': true
  '@prisma/client': true
  '@prisma/engines': true
  better-sqlite3: true
  esbuild: true
  prisma: true
  puppeteer: false
  sharp: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
