allowBuilds:
  '@openrouter/sdk': true
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  better-sqlite3: set this to true or false
  esbuild: true
  prisma: set this to true or false
  puppeteer: false
  sharp: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
